# Generated by Django 5.2.17 on 2026-09-16 17:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Org',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('org_code', models.CharField(max_length=255)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orgs', to='reconciliation.batch')),
            ],
            options={
                'ordering': ['org_code'],
                'unique_together': {('batch', 'org_code')},
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_code', models.CharField(max_length=255)),
                ('location_name', models.CharField(blank=True, max_length=255)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='reconciliation.batch')),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='reconciliation.org')),
            ],
            options={
                'ordering': ['location_code'],
                'unique_together': {('batch', 'location_code')},
            },
        ),
        migrations.CreateModel(
            name='ImportIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_file', models.CharField(max_length=255)),
                ('line_number', models.PositiveIntegerField()),
                ('field', models.CharField(blank=True, max_length=255)),
                ('raw_value', models.CharField(blank=True, max_length=255)),
                ('problem', models.TextField()),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='reconciliation.batch')),
            ],
            options={
                'ordering': ['source_file', 'line_number'],
                'indexes': [models.Index(fields=['batch'], name='reconciliat_batch_i_c3583c_idx')],
            },
        ),
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_id', models.CharField(db_index=True, max_length=255)),
                ('record_ref_raw', models.CharField(blank=True, max_length=255)),
                ('record_ref_norm', models.CharField(blank=True, db_index=True, max_length=255)),
                ('location_code_raw', models.CharField(blank=True, max_length=255)),
                ('recorded_on', models.DateField(blank=True, null=True)),
                ('recorded_on_raw', models.CharField(blank=True, max_length=255)),
                ('value', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('value_raw', models.CharField(blank=True, max_length=255)),
                ('label', models.CharField(blank=True, max_length=255)),
                ('source_line', models.PositiveIntegerField()),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='reconciliation.batch')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='entries', to='reconciliation.location')),
            ],
            options={
                'ordering': ['entry_id'],
                'indexes': [models.Index(fields=['batch', 'record_ref_norm'], name='reconciliat_batch_i_c1c970_idx')],
            },
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_id', models.CharField(db_index=True, max_length=255)),
                ('location_code_raw', models.CharField(blank=True, max_length=255)),
                ('event_date', models.DateField(blank=True, null=True)),
                ('event_date_raw', models.CharField(blank=True, max_length=255)),
                ('category_code', models.CharField(blank=True, max_length=255)),
                ('actor_id', models.CharField(blank=True, max_length=255)),
                ('base_value', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('base_value_raw', models.CharField(blank=True, max_length=255)),
                ('adjustment', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('adjustment_raw', models.CharField(blank=True, max_length=255)),
                ('total_value', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('total_value_raw', models.CharField(blank=True, max_length=255)),
                ('state', models.CharField(blank=True, max_length=255)),
                ('source_line', models.PositiveIntegerField()),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='reconciliation.batch')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='records', to='reconciliation.location')),
            ],
            options={
                'ordering': ['record_id'],
                'indexes': [models.Index(fields=['batch', 'record_id'], name='reconciliat_batch_i_2f0f43_idx')],
            },
        ),
    ]
